### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]

### ISSUE THREAD

**Issue by chulman444** [chulman444/GYST#1]
Bug:

```
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["WWW-Authenticate"]
    at storeHeader (_http_outgoing.js:412:5)
    at processHeader (_http_outgoing.js:407:3)
    at ServerResponse._storeHeader (_http_outgoing.js:313:9)
    at ServerResponse.writeHead (_http_server.js:270:8)
    at SimpleServer.requestHandler ($:/core/modules/commands/server.js:115:13)
    at Server.emit (events.js:182:13)
    at parserOnIncoming (_http_server.js:658:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

**Comment by chulman444** [comment]
In `core/modules/commands/server.js:SimpleServer.prototype.requestHandler`

```
servername = servername.replace("\n", " "); // ADD THIS
response.writeHead(401,"Authentication required",{
	"WWW-Authenticate": 'Basic realm="Please provide your username and password to login to ' + servername + '"'
});
```
